### ISSUE TITLE
Sub claim is missing error after disabling server-side sessions

### ISSUE THREAD

**Issue by deanddm** [DuendeSoftware/IdentityServer#1352]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer 6.2.3

**Which version of .NET are you using?**
.Net 6.0

**Describe the bug**
In summary, we are encountering a large amount of "sub claim missing" errors after disabling server-side sessions.
 
We had `.AddServerSideSessions()` enabled after following the quickstarts. Once we were ready for production, we purchased a Starter license and deployed to production. We only noted afterward that server-side sessions were not supported under a Starter license and attempted to disable this feature. Once live in production we had hundreds of "sub claim missing" errors occur and had to roll back the change.

I assume the issue is due to the existing cookie(s) not having state information, and once the feature is disabled, an error is thrown which blocks users from attempting to authenticate again.

Using a private browser page, or manually clearing cookies, seems to resolve the issue. However, we already have a fairly large active user base with 10K+ sessions per day and this will be difficult to communicate to all users.

We're looking for any advice on how to handle this challenge.

**To Reproduce**

- Enable the server-side sessions feature on IdentityServer, `.AddServerSideSessions()`
- Obtain an identity token using any authentication method
- (This will set relevant cookies)
- Disable the server-side sessions feature on IdentityServer
- Attempt to obtain an identity token using any authentication method

**Expected behavior**

- The authorization process is executed without any change.
- An access token is issued by IdentityServer, and the user is able to login as before.

**Log output/exception with stacktrace**

```
2023-06-27T09:09:08.725+02:00
[2023/06/27 07:09:08 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    [2023/06/27 07:09:08 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    2023-06-27T09:09:08.725+02:00
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
    Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
    2023-06-27T09:09:08.725+02:00
[2023/06/27 07:09:08 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    [2023/06/27 07:09:08 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    2023-06-27T09:09:08.725+02:00
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.AuthorizeEndpoint for /connect/authorize
    Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.AuthorizeEndpoint for /connect/authorize
    2023-06-27T09:09:08.725+02:00
[2023/06/27 07:09:08 Fatal] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    [2023/06/27 07:09:08 Fatal] Duende.IdentityServer.Hosting.IdentityServerMiddleware
    2023-06-27T09:09:08.725+02:00
Unhandled exception: sub claim is missing
    Unhandled exception: sub claim is missing
    2023-06-27T09:09:08.725+02:00
System.InvalidOperationException: sub claim is missing
   at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 80
   at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, 
   Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 153
   at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 68
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, 
   IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
    System.InvalidOperationException: sub claim is missing at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in 
    /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 80 at 
    Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, 
    Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 153 at
    Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 68 at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
    2023-06-27T09:09:08.725+02:00
[2023/06/27 07:09:08 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
    [2023/06/27 07:09:08 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
    2023-06-27T09:09:08.725+02:00
An unhandled exception has occurred while executing the request.
    An unhandled exception has occurred while executing the request.
    2023-06-27T09:09:08.725+02:00
System.InvalidOperationException: sub claim is missing
   at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 80
   at Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 153
   at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 68
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
   at IdentityServer.Startup.<>c__DisplayClass6_0.<<Configure>b__0>d.MoveNext() in /src/IdentityServer/Startup.cs:line 220
    System.InvalidOperationException: sub claim is missing at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 80 at
    Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, Boolean checkConsentResponse) 
    in /_/src/IdentityServer/Endpoints/AuthorizeEndpointBase.cs:line 153 at Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) 
    in /_/src/IdentityServer/Endpoints/AuthorizeEndpoint.cs:line 68 at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) 
    in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121 at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) 
    in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121 at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) 
    in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) 
    in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48 at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) 
    in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28 at IdentityServer.Startup.<>c__DisplayClass6_0.<<Configure>b__0>d.MoveNext() in /src/IdentityServer/Startup.cs:line 220
    2023-06-27T09:09:08.725+02:00
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Additional context**

1. We are using cookie middleware to manage authentication sessions.
2. We are using a Docker container and AWS ElasticBeanstalk to host our IdentityServer instance.
3. We have configured cookie timeout to be 1200 seconds.

**Comment by brockallen** [comment]
Another update -- the PR was approved and merged, so we'll be releasing a patch ASAP.

**Comment by brockallen** [comment]
Patch 6.2.4 has been released. Please have a look and if there is still an issue let us know. Thanks!

**Comment by deanddm** [comment]
Thanks so much @brockallen for the fast turnaround. Will get this tested soonest.

**Comment by brockallen** [comment]
@deanddm I assume no news is good news? :)
