### ISSUE TITLE
Compatibility Issue IdentityServer 5.0.5 + SqlClient 2.1.2

### ISSUE THREAD

**Issue by sopelt** [DuendeSoftware/IdentityServer#147]
**Which version of Duende IdentityServer are you using?**
5.0.5+20210c588041beab457a947e3ec35c8c5fa2390a

**Which version of .NET are you using?**
.NET Core 3.1.12

**Describe the bug**

When updating to the most recent identity server package as well as SqlClient (for included Azure MSI support) there is a conflict/API change causing startup of identity server to fail. It works for IdentityServer 5.0.0 or for SqlClient 2.0.x but neither versions are desirable workarounds.

**To Reproduce**

```
dotnet new -i Duende.IdentityServer.Templates::5.0.0
dotnet new isempty -n IdentityServer
dotnet add .\IdentityServer\IdentityServer.csproj package Microsoft.Data.SqlClient -v 2.1.2
dotnet add .\IdentityServer\IdentityServer.csproj package Duende.IdentityServer -v 5.0.5
dotnet run --project .\IdentityServer\IdentityServer.csproj
```

**Expected behavior**

IdentityServer successfully starts.

**Log output/exception with stacktrace**

```
[13:19:38 Fatal] Microsoft.AspNetCore.Hosting.Diagnostics
Application startup exception
System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.JsonWebTokens.TokenValidationResult' from assembly 'Microsoft.IdentityModel.JsonWebTokens, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Duende.IdentityServer.Validation.LicenseValidator.ValidateKey(String licenseKey)
   at Duende.IdentityServer.Validation.LicenseValidator.Initalize(ILoggerFactory loggerFactory, IdentityServerOptions options) in /_/src/IdentityServer/Validation/Default/LicenseValidator.cs:line 36
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app) in /_/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs:line 69
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app, IdentityServerMiddlewareOptions options) in /_/src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs:line 35
   at IdentityServer.Startup.Configure(IApplicationBuilder app) in C:\Dev\Local\IdentityServerSqlClientRepro\IdentityServer\Startup.cs:line 46
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

**Comment by brockallen** [comment]
Thanks, we'll have a look. At first glance, it looks like that version of `Microsoft.Data.SqlClient` is pulling in an incompatible version of the shared `Microsoft.IdentityModel.JsonWebTokens` dependency.

**Comment by sopelt** [comment]
Thanks for checking it out.
Yes, [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.2) is the one pulling in [Microsoft.IdentityModel.JsonWebTokens](https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens/6.8.0) but SqlClient 2.1.x is required for using Azure Managed Identity via connection string settings (`Authentication=Active Directory Managed Identity`).

**Comment by brockallen** [comment]
I looked into this a bit. It looks like our netcoreapp3.1 build ultimately references Microsoft.IdentityModel.JsonWebTokens (6.6.0) and given the lack of backwards compat from Microsoft.IdentityModel.JsonWebTokens (6.8.0) this problem is happening. 

I will have to chat with @leastprivilege about this -- we deliberately did not update to Microsoft.IdentityModel.JsonWebTokens (6.8.0) for our netcoreapp3.1 because of that library's historic stability and compatibility problems.

**Comment by leastprivilege** [comment]
3.1 references 5.6 because that's the version the JwtBearer and OIDC handler use. Feel free to force an update in your host, might be risky.

**Comment by brockallen** [comment]
Our assumption was that if you were running on ASP.NET Core 3.1 you would be using Microsoft.IdentityModel.JsonWebTokens v5.6 since that's what the ASP.NET Core 3.1 code uses and so that's why that's the version we build against. 

> Feel free to force an update in your host, might be risky, but worth a try.

This is in effect what's happening by referencing the newest SqlClient, and it's not ending well because Microsoft.IdentityModel.JsonWebTokens is not semver/backwards compat, which is unfortunate. This is the real culprit here.

Unfortunately I think you're only workaround at the moment @sopelt is to update to .NET 5.

**Comment by sopelt** [comment]
Thank you @brockallen and @leastprivilege . To be honest I did not notice the difference in dependencies of [the IdentityServer package](https://www.nuget.org/packages/Duende.IdentityServer/5.0.5) between netcore3.1 and net5.0.

Yes, The JWT/OIDC libs are unfortunately kind of classics for runtime compatibility issues.

Changing the target framework to 5.0 fixes my initial repro sample and identity server starts up correctly. I hope that this works for the project in question and would get in touch again if that wasn't the case.
