### ISSUE TITLE
Object reference not set to an instance of an object. at at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IPrincipal principal)

### ISSUE THREAD

**Issue by nhh-softwarehuset** [DuendeSoftware/IdentityServer#519]
**Which version of Duende IdentityServer are you using?**
5.2.2

**Which version of .NET are you using?**
ASP.NET Core Runtime 5.0.12

**Describe the bug**

exception:
```
The response has been aborted due to an unhandled application exception.

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAbortedException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternalAsync(Boolean flushEncoder)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
```

Inner exception:
```
Object reference not set to an instance of an object.

   at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IPrincipal principal) in /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 65
   at Duende.IdentityServer.Services.IUserSessionExtensions.GetLogoutNotificationContext(IUserSession session) in /_/src/IdentityServer/Extensions/IUserSessionExtensions.cs:line 28
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.<>c__DisplayClass3_0.<<Invoke>b__0>d.MoveNext() in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 73
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|226_0(HttpProtocol protocol, Stack`1 events)
```

**To Reproduce**
This is from our production environment so it is difficult to provide what actually happened in the given request, but under all curcumstances this should not throw a null reference exception.

**Expected behavior**
 not throw a null reference exception.

**Log output/exception with stacktrace**
See error description

**Additional context**
The user tried to logout in another call earlier. In this case we called HttpContext.SignOutAsync();

```
Object reference not set to an instance of an object.

   at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId(IPrincipal principal) in /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:line 65
   at Duende.IdentityServer.Services.IUserSessionExtensions.GetLogoutNotificationContext(IUserSession session) in /_/src/IdentityServer/Extensions/IUserSessionExtensions.cs:line 28
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.<>c__DisplayClass3_0.<<Invoke>b__0>d.MoveNext() in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 73
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|226_0(HttpProtocol protocol, Stack`1 events)
```

**Comment by brockallen** [comment]
Thanks, we'll have a look. Generally, the GetSubjectId() extension method should not be called unless the user is logged in, so we'll see what's going on here. Thanks.

**Comment by brockallen** [comment]
>  This is from our production environment so it is difficult to provide what actually happened in the given request, but under all curcumstances this should not throw a null reference exception.

I have looked into this, and I agree given the above call stack. I can't repro it locally. Can you?

**Comment by brockallen** [comment]
Hmm, is it possible that the principal/identity are not ClaimsPrincipal/ClaimsIdentity?

**Comment by brockallen** [comment]
@nhh-softwarehuset -- anything else to add here? If not, then I don't know what action item we have here. Thanks.

**Comment by brockallen** [comment]
Closing. If you have more info, let us know.
