### ISSUE TITLE
Unhandled exception: An item with the same key has already been added. Key: iat

### ISSUE THREAD

**Issue by devployment** [DuendeSoftware/IdentityServer#549]
**Which version of Duende IdentityServer are you using?**

5.2.3

**Which version of .NET are you using?**

net5.0

**Describe the bug**

While moving from IdSrv v4 to Duende IdSrv v5 we have the unhandled exceptions in the log. Neither the client nor the configuration was changed compared to using IdSrv 4. 

**To Reproduce**

Not sure right now. Seems to be related to handling refresh tokens from an mobile app (React native) not built in house

![image](https://user-images.githubusercontent.com/7137845/144033359-8231fb9b-7b34-436a-9e1b-3e0c1d13f637.png)

**Expected behavior**

No unhandled exceptions related to a not touched claim should be thrown. 

**Log output/exception with stacktrace**

` Unhandled exception: An item with the same key has already been added. Key: iat`

```
System.ArgumentException: An item with the same key has already been added. Key: iat
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Duende.IdentityServer.Extensions.TokenExtensions.CreateJwtPayloadDictionary(Token token, IdentityServerOptions options, ISystemClock clock, ILogger logger) in /_/src/IdentityServer/Extensions/TokenExtensions.cs:line 109
   at Duende.IdentityServer.Services.DefaultTokenCreationService.CreatePayloadAsync(Token token) in /_/src/IdentityServer/Services/Default/DefaultTokenCreationService.cs:line 85
   at Duende.IdentityServer.Services.DefaultTokenCreationService.CreateTokenAsync(Token token) in /_/src/IdentityServer/Services/Default/DefaultTokenCreationService.cs:line 76
   at Duende.IdentityServer.Services.DefaultTokenService.CreateSecurityTokenAsync(Token token) in /_/src/IdentityServer/Services/Default/DefaultTokenService.cs:line 292
   at Duende.IdentityServer.ResponseHandling.TokenResponseGenerator.ProcessRefreshTokenRequestAsync(TokenRequestValidationResult request) in /_/src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs:line 244
   at Duende.IdentityServer.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request) in /_/src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs:line 104
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 106
   at Duende.IdentityServer.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in /_/src/IdentityServer/Endpoints/TokenEndpoint.cs:line 71
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 103
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 95
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 48
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 32
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Additional context**

There is already https://github.com/DuendeSoftware/IdentityServer/issues/545 pointing in the same direction. Difference here is that we do not fiddle anywhere with `iat` claims on our own.

**Comment by brockallen** [comment]
Can you explain why you have custom code trying to add that claim into the token? It will help us understand how to handle your issue. Thanks.

**Comment by devployment** [comment]
Wait, what? We do not deal with this `iat` claim on our own at all. We have no custom code touching this claim. The referenced ticket is describing this situation, causing the same error with a different. For us this started by just using the Dudende binaries, though. 

<img width="838" alt="image" src="https://user-images.githubusercontent.com/7137845/144614148-131b6e07-cd02-4212-be3c-9a95894e8757.png">

We are not trying to set this claim anywhere. What came to mind is that we are using the RSK Saml2P add on in general. But in the context of that client that triggers the exception, no SAML is involved.

**Comment by brockallen** [comment]
I'm trying to understand what's happening so we can understand how to address this issue. It sounds like there's a custom "iat" claim being added somewhere, thus my question. Do you have a custom profile service that might be adding this claim?

**Comment by devployment** [comment]
We have a custom profile service, yes. But we are not handling the `iat` anywhere manually. But will double check that statement again.

Interestingly it seems not to happen anymore. Maybe it was related to tokens issued by another instance of IdSrv.

 > I'm trying to understand what's happening so we can understand how to address this issue.

Much appreciated. If it happens again or I have more findings I'll update here to provide more context if possible.

**Comment by brockallen** [comment]
This us a dup of #545. Will address over there.

**Comment by brockallen** [comment]
Update on this issue: https://github.com/DuendeSoftware/IdentityServer/issues/545#issuecomment-1006676459
