### ISSUE TITLE
Db context pooling on ConfigurationStore results in an exception

### ISSUE THREAD

**Issue by msschl** [DuendeSoftware/IdentityServer#645]
**Which version of Duende IdentityServer are you using?**
v6.0.0

**Which version of .NET are you using?**
.Net 6.0

**Describe the bug**

As described by the [Advanced Performance Topics Docs](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cwith-constant#limitations) the `OnConfiguring` method cannot be used with context pooling.
However, the `ConfigurationDbContext` uses the `OnConfiguring` method resulting in a runtime exception being thrown.

```cs
namespace Duende.IdentityServer.EntityFramework.DbContexts;

public class ConfigurationDbContext<TContext> : DbContext, IConfigurationDbContext
    where TContext : DbContext, IConfigurationDbContext
{
    ...

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.ConfigureWarnings(w => w.Ignore(new EventId[] { RelationalEventId.MultipleCollectionIncludeWarning }));
    }
}
```

**To Reproduce**

Enable context pooling for the `ConfigurationStore`.

**Comment by brockallen** [comment]
> As described by the Advanced Performance Topics Docs the OnConfiguring method cannot be used with context pooling.

It says "DbContext pooling has a few limitations on what can be done in the OnConfiguring method of the context.". I don't see where it says "the OnConfiguring method cannot be used with context pooling".

> resulting in a runtime exception being thrown.

Can you share the exception and call stack details, please?

**Comment by msschl** [comment]
```logs
System.InvalidOperationException: 'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at Duende.IdentityServer.EntityFramework.Stores.IdentityProviderStore.GetAllSchemeNamesAsync() in /build/vendor/IdentityServer/src/EntityFramework.Storage/Stores/IdentityProviderStore.cs:line 57
   at ASGmbH.Service.Identity.Application.Providers.Internal.DefaultSchemeProvider.GetAllProvidersAsync(CancellationToken cancellationToken)
   at ASGmbH.Service.Identity.Application.Handlers.SignInViewModelQueryHandler.GetAllProvidersAsync(SignInViewModelQuery query, AuthorizationRequest context, CancellationToken cancellationToken)
   at ASGmbH.Service.Identity.Application.Handlers.SignInViewModelQueryHandler.ExecuteAsync(SignInViewModelQuery query, CancellationToken cancellationToken)
   at ASGmbH.Service.Identity.Application.Handlers.SignInViewModelQueryHandler.HandleAsync(SignInViewModelQuery query, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ASGmbH.Service.Infrastructure.Dispatcher.QueryDispatcher.QueryAsync[TResult](IQuery`1 query, CancellationToken cancellationToken)
   at ASGmbH.Service.Identity.Controllers.BaseController.QueryAsync[TResult](IQuery`1 query)
   at ASGmbH.Service.Identity.Controllers.SignInController.OnGetAsync(String returnUrl, String providerHint)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 100
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by msschl** [comment]
> It says "DbContext pooling has a few limitations on what can be done in the OnConfiguring method of the context.". I don't see where it says "the OnConfiguring method cannot be used with context pooling".

You're right. I misread that... Sry

**Comment by brockallen** [comment]
> You're right. I misread that... Sry

Well, the exception pretty much says it :) 

Ok, we'll look into it.

**Comment by brockallen** [comment]
@msschl I just tried to repo this, but I can't. I simply set `EnablePooling` as below, but no exception. Anything I am missing to repo the issue?

```
.AddConfigurationStore(options =>
            {
                options.EnablePooling = true;
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString);
            })
```

**Comment by msschl** [comment]
This is how we add the stores:

```cs
// Add identity server configuration store and operational store
builder.IdentityServerBuilder
    .AddConfigurationStoreCache()
    // NOTE(markus): Adds the config data from DB (clients, resources)
    .AddConfigurationStore(options =>
    {
        options.EnablePooling = true;
        options.ConfigureDbContext = builder =>
        {
            builder.UseSqlServer(connectionString, configure =>
            {
                configure.MigrationsAssembly(migrationsAssembly);
            });
        };
    })
    // NOTE(markus): Adds the operational data from DB (codes, tokens, consents)
    .AddOperationalStore(options =>
    {
        options.EnablePooling = true;
        options.ConfigureDbContext = builder =>
        {
            builder.UseSqlServer(connectionString, configure =>
            {
                configure.MigrationsAssembly(migrationsAssembly);
            });
        };

        // NOTE(markus): Enable token cleanup service
        options.EnableTokenCleanup = true;
        options.TokenCleanupInterval = (int)TimeSpan.FromDays(20).TotalSeconds;
    });

return builder;
```

The exception was thrown while using the `IdentityProviderStore.GetAllSchemeNamesAsync()`

**Comment by brockallen** [comment]
Bizarre -- I just changed my code to register the way yours is (the main diff was the MigrationsAssembly) and I still don't see any exception (and I'm using the login page which uses the DB for the dynamic providers). Anything else you can think of?

**Comment by brockallen** [comment]
BTW on a side note: I think you want your call to `.AddConfigurationStoreCache()` after the call to `.AddConfigurationStore()`.

**Comment by brockallen** [comment]
I tried to repo this a diff way, and still no success. My steps:

1: install the Duende CLI templates (https://docs.duendesoftware.com/identityserver/v6/quickstarts/0_overview/)
2: create a temp directory and run "dotnet new isef" 
3: choose "Y" to seed the DB
4: edit `HostingExtensions.cs` to add `EnablePooling = true`
5: dotnet run
6: browse to https://localhost:5001/.well-known/openid-configuration to see the discovery doc (which hits the DB)

No exception. Maybe you can take these same steps to start setting up a repo?

**Comment by msschl** [comment]
The only thing I can think of is ASP Net Core Identity. We register the application db context also with pooling enabled. Also, I only get this error in the test deployment not in my local setup. The site is deployed in a container on a linux system.
Accessing the discovery document results in

```txt
System.InvalidOperationException: 'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Include[TEntity,TProperty](IQueryable`1 source, Expression`1 navigationPropertyPath)
   at Duende.IdentityServer.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync() in /build/vendor/IdentityServer/src/EntityFramework.Storage/Stores/ResourceStore.cs:line 181
   at Duende.IdentityServer.Stores.CachingResourceStore`1.<GetAllResourcesAsync>b__9_0() in /build/vendor/IdentityServer/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 70
   at Duende.IdentityServer.Services.DefaultCache`1.GetOrAddAsync(String key, TimeSpan duration, Func`1 get) in /build/vendor/IdentityServer/src/IdentityServer/Services/Default/DefaultCache.cs:line 117
   at Duende.IdentityServer.Stores.CachingResourceStore`1.GetAllResourcesAsync() in /build/vendor/IdentityServer/src/IdentityServer/Stores/Caching/CachingResourceStore.cs:line 68
   at Duende.IdentityServer.Stores.IResourceStoreExtensions.GetAllEnabledResourcesAsync(IResourceStore store) in /build/vendor/IdentityServer/src/IdentityServer/Extensions/IResourceStoreExtensions.cs:line 108
   at Duende.IdentityServer.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri) in /build/vendor/IdentityServer/src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs:line 224
   at Duende.IdentityServer.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context) in /build/vendor/IdentityServer/src/IdentityServer/Endpoints/DiscoveryEndpoint.cs:line 63
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 82
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 97
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /build/vendor/IdentityServer/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by msschl** [comment]
However, I don't think  ASP Net Core Identity's DB context pooling is the issue here. Nor the `AddDbContextPool<DataProtectionKeysContext>` should cause this error.

**Comment by brockallen** [comment]
I was able to repo this -- it's when you're calling `Database.Migrate`. It doesn't happen when you do normal DB operations, though. Can you confirm?

So, what I'd suggest is not enabling pooling in the code path that does your one-time migration.

**Comment by brockallen** [comment]
Ok, I think the inconsistent nature of this is due to the dynamic decision if an instance is pooled or not. 

In any event, I have found a possible workaround -- there's a `IsFrozen` property on the options builder that seems promising.

**Comment by msschl** [comment]
Thanks @brockallen, #646 fixes the issue for us.

 However, now we do get the warning the `OnConfiguring` method tried to hide with `RelationalEventId.MultipleCollectionIncludeWarning`:
```txt
Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
```

**Comment by brockallen** [comment]
Yes, in that case you will have to suppress that warning yourself in the host's EF config (much like it's done in the OnConfiguring in the DbCOntext).

**Comment by msschl** [comment]
To complete this thread. This is the configuration that works for us:

```cs
builder.AddConfigurationStore(options =>
{
    options.EnablePooling = true;
    options.ConfigureDbContext = builder =>
    {
        builder.UseSqlServer(connectionString, configure =>
        {
            configure.MigrationsAssembly(migrationsAssembly);
        });
        builder.ConfigureWarnings(w => w.Ignore(new EventId[] { RelationalEventId.MultipleCollectionIncludeWarning }));
    };
})
```
