### ISSUE TITLE
The key was not found in the key ring after upgrading from v4 to 5

### ISSUE THREAD

**Issue by iot-dev01** [DuendeSoftware/IdentityServer#706]
**Which version of Duende IdentityServer are you using?**
5.24

**Which version of .NET are you using?**
5.0

**Describe the bug**
After upgrading from IdentityServer 4 to 5 the connected devices getting errors fetching a new token.
The first idea was disabling the key management but it did not help.

**To Reproduce**
Upgrading from IdentityServer 4 to 5 with active logged in sessions.

Here are our configs:
```
services.AddIdentityServer(options =>
{
  options.KeyManagement.Enabled = false;
})
  .AddAspNetIdentity<ApplicationUser>()
  .AddConfigurationStore((options) =>
    options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), sql => sql.MigrationsAssembly(migrationsAssembly))
  )
  .AddOperationalStore((options) =>
  {
    options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), sql => sql.MigrationsAssembly(migrationsAssembly));
    options.EnableTokenCleanup = true;
  })
  .AddSigningCredential(rsaCert);
```
**Expected behavior**
Tokens should be managed by the system.

**Log output/exception with stacktrace**

```
Duende.IdentityServer.Stores.DefaultRefreshTokenStore
System.Security.Cryptography.CryptographicException: The key {0015a608-d444-4bdd-ab5d-2bd037b22a5a} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 109
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemAsync(String key) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 96
```

**Additional context**

**Comment by brockallen** [comment]
Your exception is from ASP.NET Data Protection, and not an IdentityServer issue. It sounds like when you migrated, you lost your data protection keys somehow.

**Comment by brockallen** [comment]
Ok, yea -- I just needed to re-check when/where we added this logic for protecting rows in that table. So yes, it looks like to me you have lost your data protection keys from your upgrade.

**Comment by brockallen** [comment]
Also, some docs on that: https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by upadhyayvipul** [comment]
I am getting the same excpetion after upgrading from V4 to 6.1.

I have disabled the Automatic key management and adding key using AddSigningCredential in startup

System.Security.Cryptography.CryptographicException: The key {be6b5373-4e0e-4785-8512-e31a6599f251} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
