### ISSUE TITLE
Problems migrating to IdSrv 6 with EF Core 6

### ISSUE THREAD

**Issue by galvesribeiro** [DuendeSoftware/IdentityServer#723]
**Which version of Duende IdentityServer are you using?**
Moving from 5.2.2 to 6.0.4

**Which version of .NET are you using?**
.Net 6 (6.0.101)

**Describe the bug**
After upgrading all Duende.IdentityServer(.*) packages to 6.0.4 and try to run `dotnet ef migrations add ...`, it fail with the following exception: 

```
Using context 'PersistedGrantDbContext'.
System.InvalidOperationException: Unable to resolve service for type 'Duende.IdentityServer.EntityFramework.Options.OperationalStoreOptions'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

The only change on the codebase I've noticed is that both `ConfigurationDbContext` and `PersistedGrantDbContext` ctor lost the second parameter (`ConfigurationStoreOptions` and `OperationalStoreOptions ` respectively). If I revert back to 5.2.2 the exception doesn't happen and it add the migration perfectly.

**Expected behavior**

The migration being added just like on 5.2.2.

**Log output/exception with stacktrace**

```
% dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/PersistedGrantDb --verbose
Using project '<PROJECT_DIR>/Identity.csproj'.
Using startup project '<PROJECT_DIR>/Identity.csproj'.
Writing '<PROJECT_DIR>/obj/Identity.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/zv/f_g8wmd128sbhbkc8j4pmc4w0000gn/T/tmpM6BB9h.tmp /verbosity:quiet /nologo <PROJECT_DIR>/Identity.csproj
Writing '<PROJECT_DIR>/obj/Identity.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/var/folders/zv/f_g8wmd128sbhbkc8j4pmc4w0000gn/T/tmpIB9nzF.tmp /verbosity:quiet /nologo <PROJECT_DIR>/Identity.csproj
Build started...
dotnet build <PROJECT_DIR>/Identity.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.08
Build succeeded.
dotnet exec --depsfile <PROJECT_DIR>/bin/Debug/net6.0/Identity.deps.json --additionalprobingpath /Users/guto/.nuget/packages --runtimeconfig <PROJECT_DIR>/bin/Debug/net6.0/Identity.runtimeconfig.json /Users/guto/.dotnet/tools/.store/dotnet-ef/6.0.2/dotnet-ef/6.0.2/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/PersistedGrantDb --assembly <PROJECT_DIR>/bin/Debug/net6.0/Identity.dll --project <PROJECT_DIR>/Identity.csproj --startup-assembly <PROJECT_DIR>/bin/Debug/net6.0/Identity.dll --startup-project <PROJECT_DIR>/Identity.csproj --project-dir <PROJECT_DIR>/ --root-namespace Identity --language C# --framework net6.0 --nullable --working-dir <PROJECT_DIR>/--verbose
Using assembly 'Identity'.
Using startup assembly 'Identity'.
Using application base '<PROJECT_DIR>/bin/Debug/net6.0'.
Using working directory '<PROJECT_DIR>/.
Using root namespace 'Identity'.
Using project directory '<PROJECT_DIR>/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'IdentityDbContextFactory'.
Found DbContext 'IdentityDbContext'.
Found IDesignTimeDbContextFactory implementation 'DataProtectionDbContextFactory'.
Found DbContext 'DataProtectionDbContext'.
Found IDesignTimeDbContextFactory implementation 'PersistedGrantDbContextFactory'.
Found DbContext 'PersistedGrantDbContext'.
Found IDesignTimeDbContextFactory implementation 'ConfigurationDbContextFactory'.
Found DbContext 'ConfigurationDbContext'.
Finding application service provider in assembly 'Identity'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Finding DbContext classes in the project...
Using DbContext factory 'PersistedGrantDbContextFactory'.
Using context 'PersistedGrantDbContext'.
System.InvalidOperationException: Unable to resolve service for type 'Duende.IdentityServer.EntityFramework.Options.OperationalStoreOptions'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext`1.OnModelCreating(ModelBuilder modelBuilder) in /_/src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs:line 65
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Duende.IdentityServer.EntityFramework.Options.OperationalStoreOptions'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

**Comment by ShahSwapnil** [comment]
Are you using IDesignTimeContextFactory? 

If you are, you can create a service provider and pass it in to the optionsBuilder. 

```
IServiceCollection services = new ServiceCollection();

services.AddIdentityServer()
        .AddOperationalStore(options => {
            options.ConfigureDbContext = b => b.UseSqlServer(connectionString, sqlOptions => {
                sqlOptions.MigrationsAssembly(assemblyName);
            });
        });

optionsBuilder.UseApplicationServiceProvider(services.BuildServiceProvider());
```

**Comment by galvesribeiro** [comment]
Yes I was. I had reverted to 5.2.4.

This was my factories on 5.2.2 that used to work fine:

```csharp
public class PersistedGrantDbContextFactory : IDesignTimeDbContextFactory<PersistedGrantDbContext>
{
    public PersistedGrantDbContext CreateDbContext(string[] args)
    {
        var optionsPersistentGrantBuilder = new DbContextOptionsBuilder<PersistedGrantDbContext>();
        optionsPersistentGrantBuilder.UseSqlServer("Data Source=db.db", opt => opt.MigrationsAssembly(typeof(Program).Assembly.FullName));
        return new PersistedGrantDbContext(optionsPersistentGrantBuilder.Options, new());
    }
}

public class ConfigurationDbContextFactory : IDesignTimeDbContextFactory<ConfigurationDbContext>
{
    public ConfigurationDbContext CreateDbContext(string[] args)
    {
        var optionsPersistentGrantBuilder = new DbContextOptionsBuilder<ConfigurationDbContext>();
        optionsPersistentGrantBuilder.UseSqlServer("Data Source=db.db", opt => opt.MigrationsAssembly(typeof(Program).Assembly.FullName));
        return new ConfigurationDbContext(optionsPersistentGrantBuilder.Options, new());
    }
}
```

Note that the ctor had an extra parameter for the Configuration\OperationStoreOptions. With the 6.0.0 the constructor doesn't have that parameter anymore.

So are you suggesting to build an `IServiceProvider` and set it on  the `DbContextOptionsBuilder<>` before pass it to the ctor?

**Comment by ShahSwapnil** [comment]
Yes I am. Sorry I should have included my entire class. 

```
public class PersistedGrantDbContextFactory : IDesignTimeDbContextFactory<PersistedGrantDbContext>
    {
        public PersistedGrantDbContext CreateDbContext(string[] args)
        {
            IConfiguration config = ConfigHelper.GetConfiguration();
            string connectionString = config.GetConnectionString("DefaultConnection");
            string? assemblyName = typeof(PersistedGrantDbContextFactory).Assembly.GetName().Name;

            DbContextOptionsBuilder<PersistedGrantDbContext> optionsBuilder = new DbContextOptionsBuilder<PersistedGrantDbContext>();
            optionsBuilder.UseSqlServer(connectionString, sqlOptions => {
                sqlOptions.MigrationsAssembly(assemblyName);
            });

            IServiceCollection services = new ServiceCollection();

            services.AddIdentityServer()
                    .AddOperationalStore(options => {
                        options.ConfigureDbContext = b => b.UseSqlServer(connectionString, sqlOptions => {
                            sqlOptions.MigrationsAssembly(assemblyName);
                        });
                    });

            optionsBuilder.UseApplicationServiceProvider(services.BuildServiceProvider());

            return new PersistedGrantDbContext(optionsBuilder.Options);
        }
    }
```

Yeah, I have one solution where we are building with IS 5.2.4 and another that we are using 6.0.4.

**Comment by ShahSwapnil** [comment]
@galvesribeiro Hmm... I was able to resolve the error. Can you check if it's the exact same error or if it has changed a little bit.

**Comment by galvesribeiro** [comment]
Oh! I was too fast 😄 Your last message come after my edit. Indeed it worked. Thank you very much! 😄 

The thing is, why do we have to register the context twice? o.O It worked before...

Anyway, now I'm unblocked at least.

Thank you! 👍🏻

**Comment by ShahSwapnil** [comment]
Well, you are really registering it only once. It just depends on the context. Because of the way EF Migrations work. I don't remember all the inner workings, but since we are using DesignTimeContextFactory, the SP is different. 

Glad I could help.

**Comment by brockallen** [comment]
Hey all -- so given that the design time DbContext factory supports the DI system, I think it's ok to close this. I agree it's wonky, but that's part of the problem with EF supporting the different models. 

If there are suggestions for making this better, we can re-visit in a minor release. Thanks.
